# Generated by Django 2.2.7 on 2020-03-17 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_name', models.CharField(max_length=20, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=1000, verbose_name='What do you need to do?')),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, verbose_name='Date of receipt')),
                ('time', models.TimeField(blank=True, verbose_name='Time of receipt')),
                ('price', models.FloatField(blank=True, max_length=10)),
                ('image', models.ImageField(default='PLEASE FIX ME', upload_to='images/')),
                ('has_been_changed', models.BooleanField(default=False)),
                ('category_name', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='EMS.Category')),
            ],
        ),
    ]
