# Generated by Django 2.2.7 on 2020-03-17 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EMS', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='name',
            field=models.CharField(blank=True, max_length=20, verbose_name='Name of receipt'),
        ),
    ]
